line 71 changed because of issue Keyword 'Capture Page Screenshot' could not be run on failure: AttributeError: 'WebDriver' object has no attribute '_execute'